name: Java CI - build

on:
  push:
    branches-ignore:
      - 'develop'
      - 'master'
      - 'dependabot/*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_PASSWORD: ${{ secrets.MVN_RELEASE_PAT }}
      run: mvn -B --settings ./.github/workflows/settings.xml test